// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypersbnccpbghzlbmtfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwZXJzYm5jY3BiZ2h6bGJtdGZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1ODkyOTcsImV4cCI6MjA3MTE2NTI5N30.9DBAyirecSD9LiRZf763p0qhrU-bhhvtRjwY3A-I3fM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});